const fs=require('fs'),path=require('path'),today=new Date().toISOString().slice(0,10),slug=today;
const feed=JSON.parse(fs.readFileSync(path.join(__dirname,'..','feed.json'),'utf8'));
if(feed.posts.find(p=>p.slug===slug)){console.log('Exists');process.exit(0)}
const pool=[[["手机拍照入门：学会这5个技巧照片立刻变好看","擦镜头、找光线、用九宫格辅助线、对焦后拉低曝光、后期微调。这5步做好照片质量提升50%。","摄影基础"],["三分法构图的万能应用：什么场景都适用","把画面横竖各分三等分共9格。主体放交叉点上比放中间有美感。拍人像眼睛对齐上三分线。","构图技巧"],["出门旅游怎么拍照好看：衣服和背景的搭配","纯色和自然环境拍最不出错、衣服颜色和背景有对比、带一条围巾或帽子做装饰品方便变换造型。","旅拍技巧"]],[["手机人像模式怎么拍才自然：虚化别开太大","人像模式的虚化边缘有时候识别不准头发会糊掉。光线好的时候关掉人像模式反而更自然更好看。","人像摄影"],["逆光拍照的正确曝光方式：别让脸变黑","逆光下对焦在人脸拉高曝光。或者对焦在天空人脸拍成剪影也很有感觉。侧逆光比正逆光好控制。","光线技巧"],["阴天怎么拍出好看的照片","阴天光线柔和没有阴影是人像拍摄的好天气。颜色偏冷可以后期加一点暖色调。阴天适合拍水景有水墨画的感觉。","光线技巧"]],[["修图软件推荐：不用学PS也能修好照片","醒图功能全面且免费、VSCO滤镜好看付费版更全、Snapseed专业免费、美图秀秀基础够用。修图原则是不修太过。","修图技巧"],["美食拍摄：让食物看起来更好吃","自然光拍摄不用闪光灯、45度斜上角或垂直俯拍、红色橙色的食物看起来更有食欲、注意背景不要太杂。","专题拍摄"],["怎么把女朋友拍好看：女生最在意的3个点","显瘦（从上往下拍）、显高（脚贴近画面底边仰拍）、显腿长（侧逆光）。多夸她好看她会觉得你拍照技术进步了。","人像摄影"]],[["夜景手机拍摄：不要用闪光灯","闪光灯拍人像又白又丑。用夜景模式长曝光+稳定手机（靠在栏杆墙上或三脚架）。找有路灯或橱窗灯的地方拍。","光线技巧"],["拍花的5个角度：不只是从上面拍","仰拍（花和天空）、水平（拍花内部花瓣纹理）、逆光（花瓣透光逆光最美）、微距（靠近拍花蕊）、带环境（人在花丛中）。","专题拍摄"],["修图的第一步是什么：裁剪","裁剪是最被低估的修图技巧。切掉多余的背景、调正水平线、改变构图比例。裁剪完再调颜色。","修图技巧"]],[["用手机拍出单反感的人像照片","找到大光比场景（一侧有光一侧暗）、让脸朝着光源、背景离人远一点就有天然虚化效果。拍摄时间是日落前1-2小时。","人像摄影"],["街拍的5个技巧：记录生活的精彩瞬间","边走边拍不要怕路人看、色彩对比强烈的场景更容易出片、等待有趣的人经过再按快门、黑白街拍有故事感。","专题拍摄"],["拍照姿势大全：手脚不知道往哪放","侧身显瘦、扶一下帽子和墨镜、靠在墙上或栏杆上、边走边回头、和身边的物品互动。自然的状态比摆拍好看。","人像摄影"]],[["春天去哪里拍照：花期和地点推荐","3月樱花（武汉无锡鼋头渚）、4月油菜花（婺源罗平）、5月薰衣草（新疆伊犁）。周末早上8点前人少。","旅拍技巧"],["怎么拍出大长腿的照片","脚贴近画面底边、身体重心放在后脚、仰拍低角度、穿高跟鞋或尖头鞋延伸腿部线条。广角镜头（手机主摄就是广角）有天然拉长效果。","人像摄影"],["下雨天拍照的好方法：雨天很有氛围感","找有玻璃窗和水珠的地方、地面倒影利用、透明伞做道具、夜景雨天路灯和霓虹倒影美爆了。","创意拍摄"]],[["宝宝和宠物怎么拍：不停动的主角拍摄技巧","用连拍模式多拍再选、蹲下来和他们在同一高度、用玩具和零食吸引注意力、自然光不用闪光灯伤眼睛。","专题拍摄"],["剪影怎么拍：夕阳下的浪漫","背景要亮主体要暗（对着天空拍背光的人）、对焦在背景最亮的地方让人变黑。动作要大一些轮廓才好看。","创意拍摄"],["VSCO调色教程：电影感色调","曝光-0.5对比度+1饱和度-0.5色温偏冷色调偏青、加一点点颗粒感增加胶片质感。这个万能公式适用80%的照片。","修图技巧"]]];
const idx=(new Date().getDate()-1)%pool.length,items=pool[idx];
const postTitle=items[0][2]+' | '+today;
feed.posts.unshift({slug,date:today,title:postTitle,items:items.map(i=>({title:i[0],desc:i[1],tag:i[2]}))});
feed.updated=today;
fs.writeFileSync(path.join(__dirname,'..','feed.json'),JSON.stringify(feed,null,2));
const html='<!DOCTYPE html><html lang="zh-CN"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>'+postTitle+'</title><style>*,*::before,*::after{box-sizing:border-box;margin:0;padding:0}:root{--bg:#fafafa;--card:#fff;--text:#1a1a2e;--t2:#666;--accent:#0d9488;--border:#e5e7eb;--r:10px}body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI","Noto Sans SC",sans-serif;background:var(--bg);color:var(--text);line-height:1.7}.container{max-width:800px;margin:0 auto;padding:0 20px}header{background:var(--card);border-bottom:1px solid var(--border);padding:20px 0;margin-bottom:32px}header a{color:var(--accent);text-decoration:none;font-size:.9rem}header h1{font-size:1.3rem;margin-top:8px}.post{background:var(--card);border:1px solid var(--border);border-radius:var(--r);padding:28px}.post .date{color:var(--t2);font-size:.8rem;margin-bottom:20px}.entry{margin-bottom:24px;padding-bottom:20px;border-bottom:1px solid var(--border)}.entry:last-child{border-bottom:none}.entry h3{font-size:1rem;margin-bottom:4px}.entry p{color:var(--t2);font-size:.9rem}.tag{display:inline-block;font-size:.72rem;padding:2px 8px;border-radius:10px;margin-left:6px;background:var(--bg);color:var(--accent)}footer{text-align:center;padding:32px 20px;color:var(--t2);font-size:.8rem}@media(max-width:600px){.post{padding:18px}}</style></head><body><header><div class="container"><a href="../index.html">← 首页</a><h1>'+postTitle+'</h1></div></header><main class="container"><article class="post"><div class="date">📅 '+today+'</div>'+items.map(i=>'<div class="entry"><h3>'+i[0]+' <span class="tag">'+i[2]+'</span></h3><p>'+i[1]+'</p></div>').join('')+'</article></main><footer><p>每日更新</p></footer></body></html>';
fs.writeFileSync(path.join(__dirname,'..','posts',slug+'.html'),html);
console.log('OK');
